platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: pal-tracker
  - name: version

outputs:
  - name: build-output

run:
  path: sh
  args:
  - -exc
  - |
    cd pal-tracker
    ./gradlew -P version=`cat ../version/number` build
    cp build/libs/pal-tracker-*.jar ../build-output
